[repository]
# The name of the github organization / person owner, e.g. tauffer-consulting.
# Must be in lower-case letters
REGISTRY_NAME = "scdi435"

# The name of this Pieces repository
REPOSITORY_NAME = "sgridchsvit-domino-pieces"
REPOSITORY_LABEL = "SmartGrid Chemosvit Pilot Project"

# The version of this Pieces release
# Attention: changing this will create a new release
VERSION = "0.1.1"
